lots of fixes and new stuff

diff --git a/tasks/do_ping.yml b/tasks/do_ping.yml
--- a/tasks/do_ping.yml
+++ b/tasks/do_ping.yml
@@ -1,12 +1,12 @@
 ---
-#info: Simple ping, one try (cygwin comp)
+#info: Simple ping, one try, only return failed
 - block:
     - name: Ping
       shell: |
         TARGET="{{ do_ping_target }}"
         # windows
         if [ -n "$(command -v systeminfo)" ]; then
-            ping "$TARGET" count 1 || exit 1
+            ping -n 1 "$TARGET" || exit 1
         # posix
         else
             ping -c1 "$TARGET" -q || exit 1
@@ -18,4 +18,4 @@
     - include_role: name=servermonkey.ww_logger
       vars:
         ww_msg: "Failed to ping {{ do_ping_target }}"
-        ww_logfile: do_ping_shells_{{ do_ping_target }}
+        ww_logfile: do_ping_shell_{{ do_ping_target }}
